apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  selector:
    matchLabels:
      app: argocd-app
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argocd-app
        image: nanajanashia/argocd-app:1.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
