apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-myapp
spec:
  selector:
    matchLabels:
      app: argocd-myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: argocd-myapp
    spec:
      containers:
      - name: argocd-myapp
        image: kishansharmacs/myhello:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
