apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-myapp-1
spec:
  selector:
    matchLabels:
      app: argocd-myapp-1
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-myapp-1
    spec:
      containers:
      - name: argocd-myapp-1
        image: kishansharmacs/myhello:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8081
